import { Body, Controller, Get, Post, Query, Req, UseGuards } from '@nestjs/common';
import { IsInt, IsOptional, IsString, MinLength } from 'class-validator';
import { AuthUser } from '../auth/auth.types';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { Roles } from '../auth/roles.decorator';
import { RolesGuard } from '../auth/roles.guard';
import { InventoryService } from './inventory.service';
class AdjustStockDto { @IsString() branchId!: string; @IsOptional() @IsString() productId?: string; @IsOptional() @IsString() variantId?: string; @IsInt() quantityChange!: number; @IsString() @MinLength(2) reason!: string; }
class TransferStockDto { @IsString() destinationBranchId!: string; @IsString() productId!: string; @IsOptional() @IsString() variantId?: string; @IsInt() quantity!: number; @IsOptional() @IsString() note?: string; }
class ReceiveStockDto { @IsOptional() @IsString() supplierId?: string; @IsString() productId!: string; @IsOptional() @IsString() variantId?: string; @IsInt() quantity!: number; @IsOptional() @IsInt() unitCost?: number; @IsOptional() @IsString() reference?: string; @IsOptional() @IsString() note?: string; }
class StockCountDto { @IsString() branchId!: string; @IsOptional() @IsString() productId?: string; @IsOptional() @IsString() variantId?: string; @IsInt() countedQuantity!: number; @IsOptional() @IsString() note?: string; }
@UseGuards(JwtAuthGuard, RolesGuard) @Roles('OWNER', 'MANAGER') @Controller('inventory')
export class InventoryController { constructor(private readonly inventory: InventoryService) {} @Post('adjustments') adjust(@Req() req: { user: AuthUser }, @Body() input: AdjustStockDto) { return this.inventory.adjust(req.user.businessId, req.user.sub, input); } @Post('stock-counts') stockCount(@Req() req: { user: AuthUser }, @Body() input: StockCountDto) { return this.inventory.stockCount(req.user.businessId, req.user.sub, input); } @Post('transfers') transfer(@Req() req: { user: AuthUser }, @Body() input: TransferStockDto) { if (!req.user.branchId) throw new Error('No active branch.'); return this.inventory.transfer(req.user.businessId, req.user.sub, req.user.branchId, input); } @Get('transfers') history(@Req() req: { user: AuthUser }) { return this.inventory.history(req.user.businessId); } @Post('receipts') receive(@Req() req: { user: AuthUser }, @Body() input: ReceiveStockDto) { if (!req.user.branchId) throw new Error('No active branch.'); return this.inventory.receive(req.user.businessId, req.user.sub, req.user.branchId, input); } @Get('receipts') receipts(@Req() req: { user: AuthUser }) { return this.inventory.receipts(req.user.businessId); } @Get('valuation') valuation(@Req() req: { user: AuthUser }, @Query('branchId') branchId: string) { return this.inventory.valuation(req.user.businessId, branchId); } @Get('reorder-suggestions') reorderSuggestions(@Req() req: { user: AuthUser }, @Query('branchId') branchId: string) { return this.inventory.reorderSuggestions(req.user.businessId, branchId); } @Get('activity') activity(@Req() req: { user: AuthUser }, @Query('branchId') branchId: string) { return this.inventory.activity(req.user.businessId, branchId); } @Get() list(@Query('branchId') branchId: string) { return this.inventory.list(branchId); } }
