ALTER TABLE "Business" ADD COLUMN "taxRateBasisPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Business" ADD COLUMN "address" TEXT;
ALTER TABLE "Business" ADD COLUMN "phone" TEXT;
ALTER TABLE "Business" ADD COLUMN "receiptPrefix" TEXT NOT NULL DEFAULT 'R';
ALTER TABLE "Business" ADD COLUMN "receiptFooter" TEXT;
ALTER TABLE "Sale" ADD COLUMN "taxTotal" INTEGER NOT NULL DEFAULT 0;
